name = "if_then_else"
description = "This is the program for If-Then-Else in Ada"
version = "0.1.0-dev"

authors = ["Vaishnav S"]
maintainers = ["Vaishnav S <vaishnav.sabari.girish@gmail.com>"]
maintainers-logins = ["Vaishnav-Sabari-Girish"]
licenses = "MIT"
website = ""
tags = ["if", "then", "else"]

executables = ["if_then_else"]
