name = "nested_procedures"
description = "Program for nested procedures in Ada"
version = "0.1.0-dev"

authors = ["Vaishnav S"]
maintainers = ["Vaishnav S <vaishnav.sabari.girish@gmail.com>"]
maintainers-logins = ["Vaishnav-Sabari-Girish"]
licenses = "MIT"
website = ""
tags = ["learn-ada", "ada"]

executables = ["nested_procedures"]
