name = "subprograms"
description = "Ada code for subprograms"
version = "0.1.0-dev"

authors = ["Vaishnav S"]
maintainers = ["Vaishnav S <vaishnav.sabari.girish@gmail.com>"]
maintainers-logins = ["Vaishnav-Sabari-Girish"]
licenses = "MIT"
website = ""
tags = ["learn-ada", "subprog", "ada"]

executables = ["subprograms"]
