name = "hello_world"
description = "This is the \"Hello World\" program in Ada"
version = "0.1.0-dev"

authors = ["Vaishnav S"]
maintainers = ["Vaishnav S <vaishnav.sabari.girish@gmail.com>"]
maintainers-logins = ["Vaishnav-Sabari-Girish"]
licenses = "MIT"
website = ""
tags = ["hello-world", "first-program"]

executables = ["hello_world"]

[[depends-on]]
gnatprove = "^15.1.0"
